image: buildpack-deps:stable

before_script:
  - apt-get update -y
  - apt-get install -y intltool
  - chmod +x *.sh

build_libs_clang_only:
  stage: build
  when: manual
  script:
    - apt-get install -y clang
    - bash ./build.sh
  variables:
    BUILD_DEPS_ONLY: 'yes'
    CC: clang
    CXX: clang++
  cache:
    key: deps_cfpp_clang
    paths: [ build_deps ]

build_libs_gcc_only:
  stage: build
  when: manual
  script:
    - apt-get install -y clang
    - bash ./build.sh
  variables:
    BUILD_DEPS_ONLY: 'yes'
    CC: gcc
    CXX: g++
  cache:
    key: deps_cfpp_gcc
    paths: [ build_deps ]

build_gcc:
  stage: build
  when: manual
  script:
    - bash ./build.sh
  variables:
    CC: gcc
    CXX: g++
  cache:
    key: deps_cfpp_gcc
    paths: [ build_deps ]
  artifacts:
    paths: [ binary ]
    expire_in: 5 days
    expose_as: transmission build result

build_clang:
  stage: build
  when: manual
  script:
    - apt-get install -y clang
    - bash ./build.sh
  variables:
    CC: clang
    CXX: clang++
  cache:
    key: deps_cfpp_clang
    paths: [ build_deps ]
  artifacts:
    paths: [ binary ]
    expire_in: 5 days
    expose_as: transmission build result

build_clang_ptversion:
  stage: build
  when: manual
  variables:
    TRANSMISSION_VER: 'master'
    MODIFY_VERSION: '2.77'
    MODIFY_PEERVER: '2770'
    CC: clang
    CXX: clang++
  script:
    - apt-get install -y clang
    - bash ./build.sh
  cache:
    key: deps_cfpp_clang
    paths: [ build_deps ]
  artifacts:
    paths: [ binary ]
    expire_in: 5 days
    expose_as: transmission build result
